# Site settings
title: 小文字
tagline: 吃饭，睡觉，遛狗头
description: 趁年轻，成为最好的自己。Happy Coding！

baseurl: ""
url: "http://blog.hacktons.cn"
paginate: 5
paginate_path: "/blog/page:num/"

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags
rss_path : /rss.xml

# user info
email: chaobinwu89@gmail.com
username: 小文字

# Build settings`
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
kramdown:
  input: GFM
  syntax_highlighter: rouge

github: "https://github.com/avenwu"
future: true
# Custom vars
version:             1.0.0
