# Site settings
title: Aven
email: me@avenwu.net
username: avenwu
baseurl: ""
url: "http://avenwu.net"
paginate: 10
paginate_path: "/blog/page:num/"

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags
rss_path : /rss.xml

# Build settings`
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
#highlighter: pygments
kramdown:
  input: GFM
  syntax_highlighter: rouge
