# Site settings
title: 小文字
email: me@avenwu.net
description: "Tech geek, Technologist, Frontend Dev, Developer, Nerdy Boy, Technokid!"
username: avenwu
baseurl: ""
url: "http://avenwu.net"
paginate: 10
paginate_path: "/blog/page:num/"

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
atom_path : /atom.xml
rss_path : /rss.xml

# Build settings`
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
highlighter: pygments
